version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DB_HOST=db  # This overrides the value in .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build: .
    command: python scraper.py
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: